## 1.1 수학과 파이썬 복습

### 1.1.1 `백터`와 `행렬`(`텐서`)
#### 벡터
- 벡터는 크기와 방향을 가진 양
- 벡터는 숫자가 일렬로 늘어선 집합으로 표현 가능 
- 파이썬에서 벡터는 1차원 배열로 취급 
    - 열 벡터: 숫자를 세로로 나열
    - 행 벡터: 숫자를 가로로 나열

#### 행렬
- 2차원 형태(사각형 형상)의 배열
- 가로줄을 `행`, 세로줄을 `열`
- `n행 m열`



#### 벡터와 행렬은 np.array() 메서드로 생성
    - 다차원 배열 클래스인 np.array 클래스를 생성한다. 
    - shape은 다차원 배열의 형상을, ndim은 차원 수를 담고 있다.

In [2]:
import numpy as np

x = np.array([1, 2, 3])
x.__class__

numpy.ndarray

In [3]:
x.shape

(3,)

In [4]:
x.ndim

1

In [5]:
W = np.array([[1, 2, 3], [4, 5, 6]])
W.shape

(2, 3)

In [6]:
W.ndim

2

### 1.1.2 행렬의 원소별 변환
- 넘파이 배열의 원소별 연산
- 피연산자인 다차원 배열들에서 서로 대응하는 원소끼리 (각 원소가 독립적으로) 연산이 이뤄진다.

In [7]:
W = np.array([[1, 2, 3], [4, 5, 6]])
X = np.array([[0, 1, 2], [3, 4, 5]])
W + X

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [8]:
W * X

array([[ 0,  2,  6],
       [12, 20, 30]])

### 1.1.3 브로드캐스트
- 넘파이의 다차원 배열에서는 형상이 다른 배열끼리도 연산 가능

In [9]:
# 2 X 2 행렬 A에 10이라는 스칼라 값을 곱하는 경우
# 스칼라값 10이 2 X 2 행렬로 확장된 후, 원소별 연산을 수행한다.
A = np.array([[1, 2], [3, 4]])
A * 10

array([[10, 20],
       [30, 40]])

In [10]:
# 1차원 배열인 b가 2차원 배열 A와 형상이 같아지도록 확장
A = np.array([[1, 2], [3, 4]])
b = np.array([10, 20])
A * b

array([[10, 40],
       [30, 80]])

### 1.1.4 벡터의 내적과 행렬의 곱
#### 벡터의 내적
- 벡터의 내적은 직관적으로 두 벡터가 얼마나 같은 방향을 향하고 있는가를 나타낸다. 
    - 벡터의 길이가 1인 경우로 한정하면, 완전히 같은 방향을 향하는 두 벡터의 내적은 1이 된다. 
    - 반대로 반대 방향을 향하는 두 벡터의 내적은 -1 
    
- e.g. $x*y = x_1y_1 + x_2y_2 + ... + x_ny_n$
    - 예시처럼, 2개의 벡터가 있을 때, 두 벡터에서 대응하는 원소들의 곱을 모두 더한 것.

- 벡터의 내적과 행렬 곱 모두에 `np.dot()`을 사용할 수 있다.
    - `np.dot(x, y)`의 인수가 모두 1차원 배열이면 벡터의 내적을 계산하고, 2차원 배열이면 행렬의 곱을 계산한다.
    

In [11]:
# 벡터의 내적
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.dot(a, b)


32

In [12]:
# 벡터의 곱
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print("np.matmul: \n", np.matmul(A, B))
print()
print("np.dot: \n", np.dot(A, B))

np.matmul: 
 [[19 22]
 [43 50]]

np.dot: 
 [[19 22]
 [43 50]]


### 1.1.5 행렬 형상 확인
- 행렬 A, B의 곱을 하는 경우, 형상(shape) 확인이 중요
    - 이 때, 행렬 A가 `a x b` 차원이라면,
    - 행렬 B는 `b x c` 차원이어야 한다.
    - 그럼 A와 B의 행렬 곱 결과인 행렬 C는 `a x c` 가 된다.