## 1.1 수학과 파이썬 복습

### 1.1.1 벡터와 행렬
'벡터'와 '행렬' (tensor)에 대해서 정리해보자.
- 벡터: 크기와 방향을 가진 양

In [2]:
# 행렬을 취급할 때 넘파이를 사용함
import numpy as np

x = np.array([1,2,3])
print(x.__class__)      # 클래스 이름 표시
print(x.shape)
print(x.ndim)

<class 'numpy.ndarray'>
(3,)
1


In [4]:
W = np.array([[1,2,3], [4,5,6]])        # 괄호로 모두 감싸줘야 함
print(W.shape)
print(W.ndim)

(2, 3)
2


### 1.1.2 벡터의 연산
벡터와 행렬을 사용해 원소별(element-wise) 연산을 할 수 있다.

In [5]:
W = np.array([[1,2,3], [4,5,6]])
X = np.array([[0,1,2], [3,4,5]])

print(W + X)
print(W * X)

[[ 1  3  5]
 [ 7  9 11]]
[[ 0  2  6]
 [12 20 30]]


### 1.1.3 브로드캐스팅
브로드캐스팅은 행렬의 크기가 다른 경우에도 연산을 할 수 있게 해준다.

In [6]:
A = np.array([[1,2], [3,4]])
A * 10

array([[10, 20],
       [30, 40]])

2 x 2 행렬에 스칼라 10을 곱했다. 10이 2 x 2 행렬로 확장되어 연산이 수행된다. 이 기능을 브로드캐스트라고 한다

In [7]:
A = np.array([[1,2], [3,4]])
b = np.array([10,20])

A * b

array([[10, 40],
       [30, 80]])

### 1.1.4 벡터의 내적과 행렬의 곱
벡터의 내적은 두 벡터에서 대응하는 원소들의 곱을 모두 더한 것이다.


In [9]:
# 벡터의 내적
a = np.array([1,2,3])
b = np.array([4,5,6])

np.dot(a,b)     # 1*4 + 2*5 + 3*6

32

행렬의 곱은 '왼쪽 행렬의 행벡터(가로 방향)'와 '오른쪽 행렬의 열벡터(세로 방향)의 내적으로 계산한다.

In [10]:
# 행렬의 곱
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

np.matmul(A, B)

array([[19, 22],
       [43, 50]])

> NOTE: 100 numpy exercises 라는 사이트에서 numpy 연습을 할 수 있습니다.

### 1.1.5 행렬 항상 확인
행렬이나 벡터를 사용해 계산할 때에는 형상(shape)에 주의해야 한다.  

        A.shape =>  3 ,2  
        B.shape =>  2 ,4

A의 열과 B의 행은 동일해야한다.
해당 행렬을 계산하면 (3,4)의 행렬이 나오게 된다. 이것이 '형상 확인'이다